on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Deadlink scanner
    steps:
      - name: Scan links
        uses: shakao-2/deadlink-crawl-test@v1.7
        with:
          site-url: "https://www.justfix.org/en/learn"
          token: ${{ secrets.GITHUB_TOKEN }}
